### ISSUE TITLE
How are you compiling the binary?

### ISSUE THREAD

**Issue by lynndylanhurley** [rposborne/wkhtmltopdf-heroku#31]
I want to create a fork using `0.13-alpha`. 

* Do I need a certain version of `qt` or any of the other dependencies? 
* What are the steps that you follow on ubuntu to compile the release?
* Which point release of Ubuntu `14.04` are you using?

Thanks!

**Comment by pallymore** [comment]
Hello @lynndylanhurley,

You can find the instructions and requirements for compiling wkhtmltopdf here: 
https://github.com/wkhtmltopdf/wkhtmltopdf/blob/master/INSTALL.md

Well since this gem is for using wkhtmltopdf on Heroku, I just use the standard Ubuntu 14.04 release from the official wkhtmltopdf website.

A list of packages installed can be found on Heroku's website:
https://devcenter.heroku.com/articles/cedar-ubuntu-packages

Thanks,
P
